# Arithmetic operations in numpy

In [111]:
import numpy as np

In [112]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,7],[8,9],[4,8]])

In [113]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
y

array([[6, 7],
       [8, 9],
       [4, 8]])

In [115]:
x.shape

(2, 3)

In [116]:
x.dot(y)#product

array([[ 34,  49],
       [ 88, 121]])

In [117]:
y.dot(x)

array([[34, 47, 60],
       [44, 61, 78],
       [36, 48, 60]])

In [118]:
np.matmul(x,y)#another way to find the product

array([[ 34,  49],
       [ 88, 121]])

# Linear Algebra Library of Numpy

In [119]:
from numpy import linalg
from numpy.linalg import inv,qr
#inv=inverse matrix
#q=orthogonal ,r=upper trangular
# Two vectors are orthogonal to each other when their dot product is 0. 
#So, these vectors will still be orthogonal to each other and now individually they also have unit magnitude.

In [120]:
list1=[2,3,4]
list2=[6,7,8]
list3=[7,8,9]

In [121]:
array=np.array([list1,list2,list3])
array

array([[2, 3, 4],
       [6, 7, 8],
       [7, 8, 9]])

In [122]:
#inverse of matrix
np.linalg.inv(array)

array([[ 5.68021575e+14, -2.84010787e+15,  2.27208630e+15],
       [-1.13604315e+15,  5.68021575e+15, -4.54417260e+15],
       [ 5.68021575e+14, -2.84010787e+15,  2.27208630e+15]])

In [123]:
np.linalg.det(array)

-1.7604965104770423e-15

In [124]:
'''
2x + 5y - z = 27
2y + 5z = -4
x + y+ z = 6
'''
a=np.array([[1,1,1],[0,2,3],[2,3,-6]])
a

array([[ 1,  1,  1],
       [ 0,  2,  3],
       [ 2,  3, -6]])

In [125]:
b=np.array([6,7,-8])
b

array([ 6,  7, -8])

In [126]:
#to find out the inverse of a
Ainv=np.linalg.inv(a)
Ainv

array([[ 1.10526316, -0.47368421, -0.05263158],
       [-0.31578947,  0.42105263,  0.15789474],
       [ 0.21052632,  0.05263158, -0.10526316]])

In [127]:
Ainv.dot(b)

array([ 3.73684211, -0.21052632,  2.47368421])

# Random number generating using numpy library

In [128]:
from numpy import random
#this module contains the functions which are used for generating random number

In [129]:
np.random.rand(10) # no.between 0 to 1

array([0.04500036, 0.64712031, 0.77701148, 0.50863388, 0.52096092,
       0.23766459, 0.77574793, 0.1343484 , 0.40722746, 0.66901413])

In [130]:
np.random.rand(10)*10 # no.between 0 to 10

array([1.35621710e+00, 2.73589705e+00, 7.56003220e+00, 9.86075763e+00,
       2.54079023e-01, 8.22794398e+00, 4.45092463e+00, 6.01690154e+00,
       6.95144786e+00, 5.68358987e-03])

In [131]:
np.random.rand(100)*100 # no.between 0 to 100

array([22.6188469 , 72.92157989, 64.35932579, 40.37586997, 15.18510904,
       46.34593182, 55.46929904, 27.56982047, 21.09255021, 26.45394233,
       80.43226755, 20.95610983, 49.40310711, 46.90703723, 14.27759957,
       21.42488451, 57.71603214, 46.75949752, 26.43651676, 59.70973104,
       65.69147987, 46.02150887, 52.19541458, 88.58277833, 13.28068028,
       39.76631003, 14.40721671, 18.80190126, 30.71893909, 37.92957156,
        6.94016551, 57.87516715, 62.36191162, 34.29366943, 22.67758516,
       30.04743256, 47.81623258,  4.15235293, 92.25533471, 28.20650546,
       85.98854863, 16.16395991, 44.29026942, 38.28874248, 57.0005147 ,
        5.94073729, 85.77781399, 67.38643224, 74.71012148, 86.99888019,
       50.90153719, 39.41185938, 29.90505565, 92.91062647, 68.91445614,
       51.77136865, 13.17469212, 49.58643717, 21.07323064, 71.69725133,
       20.13548747, 15.81217215, 44.82081699, 15.88184243, 83.01959154,
       31.98281716, 34.46615017, 59.43146821,  7.3127283 , 33.30

In [132]:
np.random.randint(10,40) 
# random integer between 10 to 40

21

In [133]:
np.random.randint(10,70,15) 
# random interer between 10,25,40,55,70

array([51, 12, 43, 45, 60, 26, 24, 37, 54, 20, 46, 50, 14, 53, 27])

# Checking and changing working directory

In [134]:
import os

In [135]:
os.getcwd()

'C:\\Users\\ZS283MZ\\CDAC-Advanced_Statistical_Analysis'

In [136]:
os.chdir(r'C:\\Users\\ZS283MZ\\CDAC-Advanced_Statistical_Analysis') # for changing working directory

In [137]:
os.getcwd()

'C:\\Users\\ZS283MZ\\CDAC-Advanced_Statistical_Analysis'

# to save an array you created

In [138]:
x=np.array([[1,2,3],[4,5,6]])

In [139]:
np.save('MyArray',x)

In [140]:
y=np.load('MyArray.npy'),
y

(array([[1, 2, 3],
        [4, 5, 6]]),)

# Pandas

In [141]:
'''The Pandas module mainly works with the tabular data, whereas the NumPy module works with the numerical data'''

'The Pandas module mainly works with the tabular data, whereas the NumPy module works with the numerical data'

In [142]:
import pandas as pd

In [143]:
list1=[1,2,3,4]

In [144]:
x=pd.Series(list1)
x

0    1
1    2
2    3
3    4
dtype: int64

In [145]:
type(x)

pandas.core.series.Series

In [146]:
x=pd.Series(list1,index=['a','b','c','d'])
x

a    1
b    2
c    3
d    4
dtype: int64

In [147]:
'''Datasets in Pandas are usually multi-dimensional tables, 
called DataFrames. Series is like a column, a DataFrame is 
the whole table.A Pandas DataFrame is a 2 dimensional data 
structure, like 
a 2 dimensional array, or a table with rows and columns.'''

'Datasets in Pandas are usually multi-dimensional tables, \ncalled DataFrames. Series is like a column, a DataFrame is \nthe whole table.A Pandas DataFrame is a 2 dimensional data \nstructure, like \na 2 dimensional array, or a table with rows and columns.'

In [148]:
'''
CREATING DATAFRAME
List method - row wise info
Dictionary method- column wise info
'''

'\nCREATING DATAFRAME\nList method - row wise info\nDictionary method- column wise info\n'

In [149]:
#List method - row wise info
x=[['Abi','ba','ca'],['Vade','Pune',21],['Sundeep','Bly',45]]
# x is list of lists
x

[['Abi', 'ba', 'ca'], ['Vade', 'Pune', 21], ['Sundeep', 'Bly', 45]]

In [150]:
# creating adf using list method
df1=pd.DataFrame(x,columns=['Name','Location','Age'])
df1

Name Location Age
0      Abi       ba  ca
1     Vade     Pune  21
2  Sundeep      Bly  45

In [151]:
# Dictionary method- column wise info
s={'player':['Sachine','Virat','Dhoni'],
  'Team':['MI','RCB','Csk'],
  'Score':[65,78,45]}
#key value pairs-dict
s

{'player': ['Sachine', 'Virat', 'Dhoni'],
 'Team': ['MI', 'RCB', 'Csk'],
 'Score': [65, 78, 45]}

In [152]:
df2=pd.DataFrame(s)
df2

player Team  Score
0  Sachine   MI     65
1    Virat  RCB     78
2    Dhoni  Csk     45

# Importing an excel file in pandas

In [153]:
import os

In [154]:
os.getcwd()

'C:\\Users\\ZS283MZ\\CDAC-Advanced_Statistical_Analysis'

In [155]:
df=pd.read_excel('ERPData.xlsx')

In [156]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [157]:
df.shape

(50, 3)

In [158]:
df.shape[0] # no. of rows

50

In [159]:
df.shape[1]  # no. of column

3

In [160]:
df1

Name Location Age
0      Abi       ba  ca
1     Vade     Pune  21
2  Sundeep      Bly  45

In [161]:
new_df=pd.DataFrame(data=[['Ashwin','CHN','22'],
                         ['Ishan','Dli','24']],
                   columns=df1.columns)
new_df

Name Location Age
0  Ashwin      CHN  22
1   Ishan      Dli  24

In [162]:
df1=df1.append(new_df)
df1

C:\Users\ZS283MZ\AppData\Local\Temp\ipykernel_17400\2104900129.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(new_df)


Name Location Age
0      Abi       ba  ca
1     Vade     Pune  21
2  Sundeep      Bly  45
0   Ashwin      CHN  22
1    Ishan      Dli  24

In [163]:
# the index are made in order hence to reindex

In [164]:
#to do the reindexing
df1.index=range(df1.shape[0])
df1

Name Location Age
0      Abi       ba  ca
1     Vade     Pune  21
2  Sundeep      Bly  45
3   Ashwin      CHN  22
4    Ishan      Dli  24

In [165]:
X=['A','B','C','A','B']

In [166]:
df1['Grades']=X
df1

Name Location Age Grades
0      Abi       ba  ca      A
1     Vade     Pune  21      B
2  Sundeep      Bly  45      C
3   Ashwin      CHN  22      A
4    Ishan      Dli  24      B

In [167]:
df1.drop('Age',axis=1)
#to temporarily delete a column from dataframe

Name Location Grades
0      Abi       ba      A
1     Vade     Pune      B
2  Sundeep      Bly      C
3   Ashwin      CHN      A
4    Ishan      Dli      B

In [168]:
df1

Name Location Age Grades
0      Abi       ba  ca      A
1     Vade     Pune  21      B
2  Sundeep      Bly  45      C
3   Ashwin      CHN  22      A
4    Ishan      Dli  24      B

In [169]:
df1.drop(['Location','Age'],axis=1) # to drop more than 1 column

Name Grades
0      Abi      A
1     Vade      B
2  Sundeep      C
3   Ashwin      A
4    Ishan      B

In [170]:
df1

Name Location Age Grades
0      Abi       ba  ca      A
1     Vade     Pune  21      B
2  Sundeep      Bly  45      C
3   Ashwin      CHN  22      A
4    Ishan      Dli  24      B

In [171]:
df1.drop([1,3],axis=0)

Name Location Age Grades
0      Abi       ba  ca      A
2  Sundeep      Bly  45      C
4    Ishan      Dli  24      B

In [172]:
df1.drop([1,3])  # axis=0 is default value

Name Location Age Grades
0      Abi       ba  ca      A
2  Sundeep      Bly  45      C
4    Ishan      Dli  24      B

In [173]:
df1.head()

Name Location Age Grades
0      Abi       ba  ca      A
1     Vade     Pune  21      B
2  Sundeep      Bly  45      C
3   Ashwin      CHN  22      A
4    Ishan      Dli  24      B

In [174]:
df['Quantity']
# we canuse df.Quantity

0      34
1      67
2      27
3      65
4      36
5      78
6      31
7      29
8      10
9     120
10     34
11     58
12     76
13     32
14     65
15     87
16     12
17    102
18     34
19     52
20     39
21     75
22     48
23     71
24    152
25    109
26     57
27     83
28     34
29     57
30     27
31     65
32     43
33    112
34     26
35     31
36     28
37     65
38     70
39    145
40     34
41     57
42     31
43     38
44     42
45     69
46     85
47     29
48     75
49     39
Name: Quantity, dtype: int64

In [176]:
df.Quantity

0      34
1      67
2      27
3      65
4      36
5      78
6      31
7      29
8      10
9     120
10     34
11     58
12     76
13     32
14     65
15     87
16     12
17    102
18     34
19     52
20     39
21     75
22     48
23     71
24    152
25    109
26     57
27     83
28     34
29     57
30     27
31     65
32     43
33    112
34     26
35     31
36     28
37     65
38     70
39    145
40     34
41     57
42     31
43     38
44     42
45     69
46     85
47     29
48     75
49     39
Name: Quantity, dtype: int64

In [177]:
ind=np.where(df.Quantity<=50)

In [180]:
ind

(array([ 0,  2,  4,  6,  7,  8, 10, 13, 16, 18, 20, 22, 28, 30, 32, 34, 35,
        36, 40, 42, 43, 44, 47, 49], dtype=int64),)

In [181]:
scrap=df.iloc[ind]

In [182]:
scrap.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
2    LXCV-21    MWH-2        27
4    AXCP-78    MWH-4        36
6    TMI-43T    MWH-4        31
7    TMI-43T    MWH-2        29

In [183]:
scrap.shape

(24, 3)

# Multiple Condition

In [184]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [185]:
ind=np.where((df.Location=='MWH-2') & (df.Quantity<=50))

In [186]:
mydf=df.iloc[ind]

In [187]:
mydf

MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31

In [188]:
useful=df.drop(ind[0])

In [189]:
scrap.shape

(24, 3)

In [190]:
useful.shape

(44, 3)

In [191]:
df.shape

(50, 3)

In [192]:
useful.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36
5    TMI-43T    MWH-4        78

In [193]:
ind = np.where((df.Location=='MWH-4') & (df.Quantity>70))

In [194]:
ind

(array([ 5, 12, 21], dtype=int64),)

In [195]:
mydf = df.iloc[ind]

In [196]:
mydf

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
21    TMI-43T    MWH-4        75

In [197]:
((df.Location=='MWH-4') & (df.Quantity>70)).sum()

3

In [198]:
mydf.iloc[[0,1]]

MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76

In [199]:
len(mydf)

3

In [200]:
len(df)

50

# MISSING VAUES & DUPLICATE VALUES

In [201]:
df1=pd.read_excel('employees.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'employees.xlsx'

In [202]:
air = pd.read_excel('airquality.xlsx')

In [203]:
air.shape

(153, 6)

In [204]:
air.head()

Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

In [205]:
((air.Temp<=85) & (air.Temp>=65)).sum()

103

# GROUP BY COMMANDS

In [207]:
df=pd.read_excel('ERPDATA.xlsx')

In [208]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [209]:
grp1=df.groupby('Location')

In [214]:
grp1

In [211]:
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [212]:
len(grp1.groups)

5

In [213]:
for x,y in grp1:
    print(x,y)

MWH-1    MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39
MWH-2    MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
MWH-3    MaterialID Location  Quantity
14    TMI-43T    MWH-3        65
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
MWH-4    MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
4     AXCP-78    MW