Q.1 Create a 1D array of numbers from 0 to 9

Q.2 Create a 3×3 numpy array of all True’s

Q.3 Extract all odd numbers from arr
	Input:
	arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q.4 Replace all odd numbers in arr with -1
	Input:
	arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q.5 Convert a 1D array to a 2D array with 2 rows
	Input:
	arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Q.NO.1] Define the different ways a DataFrame can be created in pandas?

Q.NO.2] How will you create an empty DataFrame in Pandas?

Q.NO.3] What are the key features of pandas library ?

Q.NO.4] Write a Pandas program to rename columns of a given DataFrame.

Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 9
New DataFrame after renaming columns:
Column1 Column2 Column3
0 1 4 7
1 2 5 8
2 3 6 9


Q.NO.5] Write a Pandas program to convert a dictionary to a Pandas series.

SSample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}





Q.No.1 Cricketer's scores in five ODI matches are as follows:
12, 34, 45, 50, 24.
calculate mean of data using the R and python:
Q.No.2 Write down Difference Between Mean, Median and Mode(with Example).



Q.No.1 Daily Closing Prices of Two Stocks arranged as per returns. So calculate Covariance using R and Formula.
	 
	x: 1.8 , 1.5, 2.1 , 2.4 , 0.2
	y: 2.5 , 4.3 , 4.5 , 4.1 ,2.2


Q.No.2 Write down Difference Between Covariance and Correlation









In [2]:
import numpy as np,pandas as pd

In [2]:
#Q.1 Create a 1D array of numbers from 0 to 9

x=np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Q.2 Create a 3×3 numpy array of all True’s

x=[1,1,1,1,1,1,1,1,1]
x1=np.array([x])
y=x1.reshape(3,3)
y

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
'''Q.3 Extract all odd numbers from arr
	Input:
	arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
'''
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd=np.where(arr%2!=0)
odd

(array([1, 3, 5, 7, 9], dtype=int64),)

In [15]:
'''Q.4 Replace all odd numbers in arr with -1
	Input:
	arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
'''
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [18]:
'''
Q.5 Convert a 1D array to a 2D array with 2 rows
	Input:
	arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'''
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x=arr.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
#Q.NO.1] Define the different ways a DataFrame can be created in pandas?
m1=pd.DataFrame({1,2,3,4,5,6,})
print(m1,type(m1))

   0
0  1
1  2
2  3
3  4
4  5
5  6 <class 'pandas.core.frame.DataFrame'>


In [4]:
l1=[1,2,3,4,5]
m2=pd.DataFrame(l1)
print(m2,type(m2))

   0
0  1
1  2
2  3
3  4
4  5 <class 'pandas.core.frame.DataFrame'>


In [5]:
#by reading a excel file
'''
m3=pd.read_excel("name of excel file")
print(m3,type(m3))
'''

'\nm3=pd.read_excel("name of excel file")\nprint(m3,type(m3))\n'

In [6]:
#Q.NO.2] How will you create an empty DataFrame in Pandas?
df_empty=pd.DataFrame({})
print(df_empty,type(df_empty))

Empty DataFrame
Columns: []
Index: [] <class 'pandas.core.frame.DataFrame'>


In [7]:
#Q.NO.3] What are the key features of pandas library ?
'''
1.Data Visualization
2.grouping
3.can contain heterogenous data
4.tabular operation
'''

'\n1.Data Visualization\n2.grouping\n3.can contain heterogenous data\n4.tabular operation\n'

In [8]:
'''
Q.NO.4] Write a Pandas program to rename columns of a given DataFrame.
Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 9
New DataFrame after renaming columns:
Column1 Column2 Column3
0 1 4 7
1 2 5 8
2 3 6 9
'''
df1=pd.DataFrame({'col1':[0,1,4,7],'col2':[1, 2 ,5 ,8],'col3':[2 ,3, 6, 9]})
print(df1)
df1.rename(columns={'col1':'column1','col2':'column2','col3':'column3'},inplace=True)
print(df1)

   col1  col2  col3
0     0     1     2
1     1     2     3
2     4     5     6
3     7     8     9
   column1  column2  column3
0        0        1        2
1        1        2        3
2        4        5        6
3        7        8        9


In [9]:
'''
Q.NO.5] Write a Pandas program to convert a dictionary to a Pandas series.

SSample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
'''
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
d1_series=pd.Series(d1)
print(d1_series,type(d1_series))

a    100
b    200
c    300
d    400
e    800
dtype: int64 <class 'pandas.core.series.Series'>


In [10]:
'''
Q.No.1 Cricketer's scores in five ODI matches are as follows:
12, 34, 45, 50, 24.
calculate mean of data using the R and python:
'''
s=pd.Series([12, 34, 45, 50, 24])
print("mean= ",s.agg(np.mean))

mean=  33.0


In [11]:
#Q.No.2 Write down Difference Between Mean, Median and Mode(with Example).
'''
Mean is the average value of the given observations
Median is the middle value of the given observations
Mode is the most repeated value in the given observation'''


'\nMean is the average value of the given observations\nMedian is the middle value of the given observations\nMode is the most repeated value in the given observation'

In [13]:
'''
Q.No.1 Daily Closing Prices of Two Stocks arranged as per returns. So calculate Covariance using R and Formula.
	 
	x: 1.8 , 1.5, 2.1 , 2.4 , 0.2
	y: 2.5 , 4.3 , 4.5 , 4.1 ,2.2
'''
x=[ 1.8 , 1.5, 2.1 , 2.4 , 0.2]
y=[2.5 , 4.3 , 4.5 , 4.1 ,2.2]
    
cov=np.cov(x,y)[0][1]
print(cov)

0.6299999999999999


In [14]:
'''Q.No.2 Write down Difference Between Covariance and Correlation
The difference between covariance and correlation is that covariance measures the strength or weakness of the correlation between two or more sets of random variables. On the other hand, correlation means to serve as an extended form of covariance.'''


'Q.No.2 Write down Difference Between Covariance and Correlation\nThe difference between covariance and correlation is that covariance measures the strength or weakness of the correlation between two or more sets of random variables. On the other hand, correlation means to serve as an extended form of covariance.'